apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: webrtc-receiver
  namespace: plarail2021
spec:
  image: ghcr.io/ueckoken/plarail2022-receiver-test
  interval: 1m0s
