sensors:
# それぞれのSensorを通過した時に対応するblockをどうするかを指定
  - name: shinjuku_d1
    block: shinjuku_sakurajosui_up
    state: open
  - name: shinjuku_d2
    block: shinjuku_sakurajosui_down
    state: close
  - name: sakurajosui_d1
    block: shinjuku_sakurajosui_down
    state: open
  - name: sakurajosui_d2
    block: sakurajosui_chofu_down
    state: close
  - name: sakurajosui_d3
    block: sakurajosui_chofu_up
    state: open
  - name: sakurajosui_d4
    block: shinjuku_sakurajosui_up
    state: close
  - name: chofu_d1
    block: sakurajosui_chofu_down
    state: open
  - name: chofu_d2
    block: chofu_hachioji_down
    state: close
  - name: chofu_d3
    block: chofu_hashimoto_down
    state: close
  - name: chofu_d4
    block: chofu_hachioji_up
    state: open
  - name: chofu_d5
    block: chofu_hashimoto_up
    state: open
  - name: chofu_d6
    block: sakurajosui_chofu_up
    state: close
  - name: hashimoto_d1
    block: chofu_hashimoto_down
    state: open
  - name: hashimoto_d2
    block: chofu_hashimoto_up
    state: close
  - name: hachioji_d1
    block: chofu_hachioji_down
    state: open
  - name: hachioji_d2
    block: chofu_hachioji_up
    state: close
# 若葉台車両基地は変則的な動作をするためここでは未定義