apiVersion: v1
kind: Service
metadata:
  name: soft-backend-json2grpc
  namespace: plarail2021
  labels:
    app: soft-backend-json2grpc
spec:
  type: LoadBalancer
  selector:
    app: soft-backend-json2grpc
  ports:
    - port: 54322
      protocol: TCP
      targetPort: 8080
