apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-backend-internal
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: soft-backend-internal
  template:
    metadata:
      labels:
        app: soft-backend-internal
    spec:
      containers:
        - name: soft-backend-internal
          image: ghcr.io/ueckoken/plarail2022-internal:f54c2bd-1668677172 # {"$imagepolicy": "plarail2021:internal"}
          imagePullPolicy: Always
          ports:
            - containerPort: 54321
