apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-operation
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: auto-operation
  template:
    metadata:
      labels:
        app: auto-operation
    spec:
      containers:
        - name: soft-backend-auto-operation
          image: ghcr.io/ueckoken/plarail2022-auto-operation:8eb9054-1668669047 # {"$imagepolicy": "plarail2021:auto-operation"}
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: auto-operation-env
