apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auto-operation-nginx
  namespace: plarail2021
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: operate.chofufes2022.ueckoken.club
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auto-operation
                port:
                  number: 8080
  tls:
    - hosts:
        - "*.chofufes2022.ueckoken.club"
        - "chofufes2022.ueckoken.club"
      secretName: traefik-6cc55f75d7-njv8p
