apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auto-operation
  namespace: plarail2021
spec:
  routes:
  - kind: Rule
    match: Host(`operate.chofufes2022.gotti.dev`)
    services:
    - name: plarail2021-soft-backend-auto-operation
      port: 80
