apiVersion: v1
kind: Service
metadata:
  name: auto-operation
  namespace: plarail2021
  labels:
    app: auto-operation
spec:
  type: ClusterIP
  selector:
    app: auto-operation
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 50050
