apiVersion: v1
kind: Service
metadata:
  name: plarail2021-soft-backend-auto-operation
  namespace: plarail2021
  labels:
    app: plarail2021-soft-backend-auto-operation
spec:
  type: NodePort
  selector:
    app: plarail2021-soft-backend-auto-operation
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 50050
