# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62lock.proto\"\x81\x01\n\x12NotifyStateRequest\x12(\n\x05state\x18\x02 \x01(\x0e\x32\x19.NotifyStateRequest.State\x12\x16\n\x05\x62lock\x18\x03 \x01(\x0b\x32\x07.Blocks\")\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\"x\n\x13NotifyStateResponse\x12/\n\x08response\x18\x01 \x01(\x0e\x32\x1d.NotifyStateResponse.Response\"0\n\x08Response\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"\xe9\x02\n\x06\x42locks\x12 \n\x07\x62lockId\x18\x03 \x01(\x0e\x32\x0f.Blocks.BlockId\"\xbc\x02\n\x07\x42lockId\x12\x0b\n\x07unknown\x10\x00\x12\x0f\n\x0bshinjuku_b1\x10\x01\x12\x0f\n\x0bshinjuku_b2\x10\x02\x12\x12\n\x0esakurajosui_b1\x10\x0b\x12\x12\n\x0esakurajosui_b2\x10\x0c\x12\x12\n\x0esakurajosui_b3\x10\r\x12\x12\n\x0esakurajosui_b4\x10\x0e\x12\x12\n\x0esakurajosui_b5\x10\x0f\x12\x12\n\x0esakurajosui_b6\x10\x10\x12\x0c\n\x08\x63hofu_b1\x10\x15\x12\x0c\n\x08\x63hofu_b2\x10\x16\x12\x0c\n\x08\x63hofu_b3\x10\x17\x12\x0c\n\x08\x63hofu_b4\x10\x18\x12\x0c\n\x08\x63hofu_b5\x10\x19\x12\x10\n\x0chashimoto_b1\x10\x1f\x12\x10\n\x0chashimoto_b2\x10 \x12\x0f\n\x0bhachioji_b1\x10)\x12\x0f\n\x0bhashioji_b2\x10*2L\n\x0e\x42lockStateSync\x12:\n\x0bNotifyState\x12\x13.NotifyStateRequest\x1a\x14.NotifyStateResponse\"\x00\x42\x08Z\x06./specb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'block_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./spec'
  _NOTIFYSTATEREQUEST._serialized_start=16
  _NOTIFYSTATEREQUEST._serialized_end=145
  _NOTIFYSTATEREQUEST_STATE._serialized_start=104
  _NOTIFYSTATEREQUEST_STATE._serialized_end=145
  _NOTIFYSTATERESPONSE._serialized_start=147
  _NOTIFYSTATERESPONSE._serialized_end=267
  _NOTIFYSTATERESPONSE_RESPONSE._serialized_start=219
  _NOTIFYSTATERESPONSE_RESPONSE._serialized_end=267
  _BLOCKS._serialized_start=270
  _BLOCKS._serialized_end=631
  _BLOCKS_BLOCKID._serialized_start=315
  _BLOCKS_BLOCKID._serialized_end=631
  _BLOCKSTATESYNC._serialized_start=633
  _BLOCKSTATESYNC._serialized_end=709
# @@protoc_insertion_point(module_scope)
