# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62lock.proto\"J\n\rBlockAndState\x12\x19\n\x07\x62lockId\x18\x03 \x01(\x0e\x32\x08.BlockId\x12\x1e\n\x05state\x18\x02 \x01(\x0e\x32\x0f.BlockStateEnum\"8\n\x17UpdateBlockStateRequest\x12\x1d\n\x05state\x18\x01 \x01(\x0b\x32\x0e.BlockAndState\"\x1a\n\x18UpdateBlockStateResponse\"8\n\x17NotifyBlockStateRequest\x12\x1d\n\x05state\x18\x01 \x01(\x0b\x32\x0e.BlockAndState\"\x1a\n\x18NotifyBlockStateResponse*S\n\x0e\x42lockStateEnum\x12\x16\n\x12\x42LOCKSTATE_UNKNOWN\x10\x00\x12\x13\n\x0f\x42LOCKSTATE_OPEN\x10\x01\x12\x14\n\x10\x42LOCKSTATE_CLOSE\x10\x02*\xbc\x02\n\x07\x42lockId\x12\x0b\n\x07unknown\x10\x00\x12\x0f\n\x0bshinjuku_b1\x10\x01\x12\x0f\n\x0bshinjuku_b2\x10\x02\x12\x12\n\x0esakurajosui_b1\x10\x0b\x12\x12\n\x0esakurajosui_b2\x10\x0c\x12\x12\n\x0esakurajosui_b3\x10\r\x12\x12\n\x0esakurajosui_b4\x10\x0e\x12\x12\n\x0esakurajosui_b5\x10\x0f\x12\x12\n\x0esakurajosui_b6\x10\x10\x12\x0c\n\x08\x63hofu_b1\x10\x15\x12\x0c\n\x08\x63hofu_b2\x10\x16\x12\x0c\n\x08\x63hofu_b3\x10\x17\x12\x0c\n\x08\x63hofu_b4\x10\x18\x12\x0c\n\x08\x63hofu_b5\x10\x19\x12\x10\n\x0chashimoto_b1\x10\x1f\x12\x10\n\x0chashimoto_b2\x10 \x12\x0f\n\x0bhachioji_b1\x10)\x12\x0f\n\x0bhachioji_b2\x10*2^\n\x11\x42lockStateManager\x12I\n\x10UpdateBlockState\x12\x18.UpdateBlockStateRequest\x1a\x19.UpdateBlockStateResponse\"\x00\x32\x63\n\x16\x42lockStateNotification\x12I\n\x10NotifyBlockState\x12\x18.NotifyBlockStateRequest\x1a\x19.NotifyBlockStateResponse\"\x00\x42\x08Z\x06./specb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'block_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./spec'
  _BLOCKSTATEENUM._serialized_start=263
  _BLOCKSTATEENUM._serialized_end=346
  _BLOCKID._serialized_start=349
  _BLOCKID._serialized_end=665
  _BLOCKANDSTATE._serialized_start=15
  _BLOCKANDSTATE._serialized_end=89
  _UPDATEBLOCKSTATEREQUEST._serialized_start=91
  _UPDATEBLOCKSTATEREQUEST._serialized_end=147
  _UPDATEBLOCKSTATERESPONSE._serialized_start=149
  _UPDATEBLOCKSTATERESPONSE._serialized_end=175
  _NOTIFYBLOCKSTATEREQUEST._serialized_start=177
  _NOTIFYBLOCKSTATEREQUEST._serialized_end=233
  _NOTIFYBLOCKSTATERESPONSE._serialized_start=235
  _NOTIFYBLOCKSTATERESPONSE._serialized_end=261
  _BLOCKSTATEMANAGER._serialized_start=667
  _BLOCKSTATEMANAGER._serialized_end=761
  _BLOCKSTATENOTIFICATION._serialized_start=763
  _BLOCKSTATENOTIFICATION._serialized_end=862
# @@protoc_insertion_point(module_scope)
