# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statesync.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstatesync.proto\"(\n\x07Station\x12\x1d\n\tstationId\x18\x01 \x01(\x0e\x32\n.StationId\"J\n\rPointAndState\x12\x19\n\x07station\x18\x01 \x01(\x0b\x32\x08.Station\x12\x1e\n\x05state\x18\x02 \x01(\x0e\x32\x0f.PointStateEnum\"8\n\x17UpdatePointStateRequest\x12\x1d\n\x05state\x18\x01 \x01(\x0b\x32\x0e.PointAndState\"\x1a\n\x18UpdatePointStateResponse\"8\n\x17NotifyPointStateRequest\x12\x1d\n\x05state\x18\x01 \x01(\x0b\x32\x0e.PointAndState\"\x1a\n\x18NotifyPointStateResponse*\xfe\x02\n\tStationId\x12\x15\n\x11stationid_unknown\x10\x00\x12\x0f\n\x0bshinjuku_s1\x10\x02\x12\x0f\n\x0bshinjuku_s2\x10\x03\x12\x12\n\x0esakurajosui_p1\x10\x0b\x12\x12\n\x0esakurajosui_p2\x10\x0c\x12\x12\n\x0esakurajosui_s0\x10\r\x12\x12\n\x0esakurajosui_s1\x10\x0e\x12\x12\n\x0esakurajosui_s2\x10\x0f\x12\x12\n\x0esakurajosui_s3\x10\x10\x12\x12\n\x0esakurajosui_s4\x10\x11\x12\x12\n\x0esakurajosui_s5\x10\x12\x12\x0c\n\x08\x63hofu_p1\x10\x15\x12\x0c\n\x08\x63hofu_s0\x10\x16\x12\x0c\n\x08\x63hofu_s1\x10\x17\x12\x0c\n\x08\x63hofu_s2\x10\x18\x12\x0c\n\x08\x63hofu_s3\x10\x19\x12\x0c\n\x08\x63hofu_s4\x10\x1a\x12\x10\n\x0chashimoto_s1\x10\x1f\x12\x10\n\x0chashimoto_s2\x10 \x12\x0f\n\x0bhachioji_s1\x10)\x12\x0f\n\x0bhachioji_s2\x10**O\n\x0ePointStateEnum\x12\x16\n\x12POINTSTATE_UNKNOWN\x10\x00\x12\x11\n\rPOINTSTATE_ON\x10\x01\x12\x12\n\x0ePOINTSTATE_OFF\x10\x02\x32Y\n\x0cStateManager\x12I\n\x10UpdatePointState\x12\x18.UpdatePointStateRequest\x1a\x19.UpdatePointStateResponse\"\x00\x32\x63\n\x16PointStateNotification\x12I\n\x10NotifyPointState\x12\x18.NotifyPointStateRequest\x1a\x19.NotifyPointStateResponse\"\x00\x42\x08Z\x06./specb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statesync_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./spec'
  _STATIONID._serialized_start=310
  _STATIONID._serialized_end=692
  _POINTSTATEENUM._serialized_start=694
  _POINTSTATEENUM._serialized_end=773
  _STATION._serialized_start=19
  _STATION._serialized_end=59
  _POINTANDSTATE._serialized_start=61
  _POINTANDSTATE._serialized_end=135
  _UPDATEPOINTSTATEREQUEST._serialized_start=137
  _UPDATEPOINTSTATEREQUEST._serialized_end=193
  _UPDATEPOINTSTATERESPONSE._serialized_start=195
  _UPDATEPOINTSTATERESPONSE._serialized_end=221
  _NOTIFYPOINTSTATEREQUEST._serialized_start=223
  _NOTIFYPOINTSTATEREQUEST._serialized_end=279
  _NOTIFYPOINTSTATERESPONSE._serialized_start=281
  _NOTIFYPOINTSTATERESPONSE._serialized_end=307
  _STATEMANAGER._serialized_start=775
  _STATEMANAGER._serialized_end=864
  _POINTSTATENOTIFICATION._serialized_start=866
  _POINTSTATENOTIFICATION._serialized_end=965
# @@protoc_insertion_point(module_scope)
