# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import statesync_pb2 as statesync__pb2


class ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Command2Internal = channel.unary_unary(
                '/Control/Command2Internal',
                request_serializer=statesync__pb2.RequestSync.SerializeToString,
                response_deserializer=statesync__pb2.ResponseSync.FromString,
                )


class ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Command2Internal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Command2Internal': grpc.unary_unary_rpc_method_handler(
                    servicer.Command2Internal,
                    request_deserializer=statesync__pb2.RequestSync.FromString,
                    response_serializer=statesync__pb2.ResponseSync.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Command2Internal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/Command2Internal',
            statesync__pb2.RequestSync.SerializeToString,
            statesync__pb2.ResponseSync.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
