apiVersion: apps/v1
kind: Deployment
metadata:
  name: plarail2021-positioning
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: plarail2021-positioning
  template:
    metadata:
      labels:
        app: plarail2021-positioning
    spec:
      containers:
        - name: plarail2021-positioning
          image: ghcr.io/ueckoken/plarail2021-soft-positioning:b897376-1637561919 # {"$imagepolicy": "plarail2021:positioning"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB
              value: "host=127.0.0.1 user=gorm password=gorm dbname=gorm port=5432 sslmode=disable TimeZone=Asia/Tokyo"
        - name: postgresql
          image: postgres:15.0
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: "gorm"
            - name: POSTGRES_PASSWORD
              value: "gorm"
            - name: POSTGRES_DB
              value: "gorm"
