apiVersion: v1
kind: ServiceAccount
metadata:
  name: logviewer
  namespace: plarail2021
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logviewer
  namespace: plarail2021
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logviewer
  namespace: plarail2021
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: logviewer
subjects:
- kind: ServiceAccount
  name: logviewer
