apiVersion: v1
kind: Endpoints
metadata:
  name: control-internal
  namespace: monitoring
  labels:
    app: control-internal
subsets:
- addresses:
  - ip: 130.153.17.100
  ports:
  - name: prom
    port: 443
    protocol: TCP
