apiVersion: v1
kind: Service
metadata:
  name: control-internal
  namespace: monitoring
  labels:
    app: control-internal
spec:
  externalName: 130.153.17.100
  ports:
  - name: prom
    port: 80
    protocol: TCP
    targetPort: 443
  type: ExternalName
