// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: proto/ats.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendStatusRequest_SensorName int32

const (
	SendStatusRequest_unknown        SendStatusRequest_SensorName = 0
	SendStatusRequest_shinjuku_d1    SendStatusRequest_SensorName = 1
	SendStatusRequest_shinjuku_d2    SendStatusRequest_SensorName = 2
	SendStatusRequest_sakurajosui_d1 SendStatusRequest_SensorName = 11
	SendStatusRequest_sakurajosui_d2 SendStatusRequest_SensorName = 12
	SendStatusRequest_sakurajosui_d3 SendStatusRequest_SensorName = 13
	SendStatusRequest_sakurajosui_d4 SendStatusRequest_SensorName = 14
	SendStatusRequest_sakurajosui_d5 SendStatusRequest_SensorName = 15
	SendStatusRequest_sakurajosui_d6 SendStatusRequest_SensorName = 16
	SendStatusRequest_chofu_d1       SendStatusRequest_SensorName = 21
	SendStatusRequest_chofu_d2       SendStatusRequest_SensorName = 22
	SendStatusRequest_chofu_d3       SendStatusRequest_SensorName = 23
	SendStatusRequest_chofu_d4       SendStatusRequest_SensorName = 24
	SendStatusRequest_chofu_d5       SendStatusRequest_SensorName = 25
	SendStatusRequest_hashimoto_d1   SendStatusRequest_SensorName = 31
	SendStatusRequest_hashimoto_d2   SendStatusRequest_SensorName = 32
	SendStatusRequest_hachioji_d1    SendStatusRequest_SensorName = 41
	SendStatusRequest_hachioji_d2    SendStatusRequest_SensorName = 42
)

// Enum value maps for SendStatusRequest_SensorName.
var (
	SendStatusRequest_SensorName_name = map[int32]string{
		0:  "unknown",
		1:  "shinjuku_d1",
		2:  "shinjuku_d2",
		11: "sakurajosui_d1",
		12: "sakurajosui_d2",
		13: "sakurajosui_d3",
		14: "sakurajosui_d4",
		15: "sakurajosui_d5",
		16: "sakurajosui_d6",
		21: "chofu_d1",
		22: "chofu_d2",
		23: "chofu_d3",
		24: "chofu_d4",
		25: "chofu_d5",
		31: "hashimoto_d1",
		32: "hashimoto_d2",
		41: "hachioji_d1",
		42: "hachioji_d2",
	}
	SendStatusRequest_SensorName_value = map[string]int32{
		"unknown":        0,
		"shinjuku_d1":    1,
		"shinjuku_d2":    2,
		"sakurajosui_d1": 11,
		"sakurajosui_d2": 12,
		"sakurajosui_d3": 13,
		"sakurajosui_d4": 14,
		"sakurajosui_d5": 15,
		"sakurajosui_d6": 16,
		"chofu_d1":       21,
		"chofu_d2":       22,
		"chofu_d3":       23,
		"chofu_d4":       24,
		"chofu_d5":       25,
		"hashimoto_d1":   31,
		"hashimoto_d2":   32,
		"hachioji_d1":    41,
		"hachioji_d2":    42,
	}
)

func (x SendStatusRequest_SensorName) Enum() *SendStatusRequest_SensorName {
	p := new(SendStatusRequest_SensorName)
	*p = x
	return p
}

func (x SendStatusRequest_SensorName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendStatusRequest_SensorName) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ats_proto_enumTypes[0].Descriptor()
}

func (SendStatusRequest_SensorName) Type() protoreflect.EnumType {
	return &file_proto_ats_proto_enumTypes[0]
}

func (x SendStatusRequest_SensorName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendStatusRequest_SensorName.Descriptor instead.
func (SendStatusRequest_SensorName) EnumDescriptor() ([]byte, []int) {
	return file_proto_ats_proto_rawDescGZIP(), []int{0, 0}
}

type SendStatusResponse_Response int32

const (
	SendStatusResponse_UNKNOWN SendStatusResponse_Response = 0
	SendStatusResponse_SUCCESS SendStatusResponse_Response = 1
	SendStatusResponse_FAILED  SendStatusResponse_Response = 2
)

// Enum value maps for SendStatusResponse_Response.
var (
	SendStatusResponse_Response_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILED",
	}
	SendStatusResponse_Response_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILED":  2,
	}
)

func (x SendStatusResponse_Response) Enum() *SendStatusResponse_Response {
	p := new(SendStatusResponse_Response)
	*p = x
	return p
}

func (x SendStatusResponse_Response) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SendStatusResponse_Response) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ats_proto_enumTypes[1].Descriptor()
}

func (SendStatusResponse_Response) Type() protoreflect.EnumType {
	return &file_proto_ats_proto_enumTypes[1]
}

func (x SendStatusResponse_Response) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SendStatusResponse_Response.Descriptor instead.
func (SendStatusResponse_Response) EnumDescriptor() ([]byte, []int) {
	return file_proto_ats_proto_rawDescGZIP(), []int{1, 0}
}

type SendStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sensor SendStatusRequest_SensorName `protobuf:"varint,1,opt,name=sensor,proto3,enum=SendStatusRequest_SensorName" json:"sensor,omitempty"`
}

func (x *SendStatusRequest) Reset() {
	*x = SendStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatusRequest) ProtoMessage() {}

func (x *SendStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatusRequest.ProtoReflect.Descriptor instead.
func (*SendStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_ats_proto_rawDescGZIP(), []int{0}
}

func (x *SendStatusRequest) GetSensor() SendStatusRequest_SensorName {
	if x != nil {
		return x.Sensor
	}
	return SendStatusRequest_unknown
}

type SendStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response SendStatusResponse_Response `protobuf:"varint,1,opt,name=response,proto3,enum=SendStatusResponse_Response" json:"response,omitempty"`
}

func (x *SendStatusResponse) Reset() {
	*x = SendStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatusResponse) ProtoMessage() {}

func (x *SendStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatusResponse.ProtoReflect.Descriptor instead.
func (*SendStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_ats_proto_rawDescGZIP(), []int{1}
}

func (x *SendStatusResponse) GetResponse() SendStatusResponse_Response {
	if x != nil {
		return x.Response
	}
	return SendStatusResponse_UNKNOWN
}

var File_proto_ats_proto protoreflect.FileDescriptor

var file_proto_ats_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8c, 0x03, 0x0a, 0x11, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x22, 0xbf,
	0x02, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x73, 0x68,
	0x69, 0x6e, 0x6a, 0x75, 0x6b, 0x75, 0x5f, 0x64, 0x31, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x73,
	0x68, 0x69, 0x6e, 0x6a, 0x75, 0x6b, 0x75, 0x5f, 0x64, 0x32, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e,
	0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x6a, 0x6f, 0x73, 0x75, 0x69, 0x5f, 0x64, 0x31, 0x10, 0x0b,
	0x12, 0x12, 0x0a, 0x0e, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x6a, 0x6f, 0x73, 0x75, 0x69, 0x5f,
	0x64, 0x32, 0x10, 0x0c, 0x12, 0x12, 0x0a, 0x0e, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x6a, 0x6f,
	0x73, 0x75, 0x69, 0x5f, 0x64, 0x33, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x73, 0x61, 0x6b, 0x75,
	0x72, 0x61, 0x6a, 0x6f, 0x73, 0x75, 0x69, 0x5f, 0x64, 0x34, 0x10, 0x0e, 0x12, 0x12, 0x0a, 0x0e,
	0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x6a, 0x6f, 0x73, 0x75, 0x69, 0x5f, 0x64, 0x35, 0x10, 0x0f,
	0x12, 0x12, 0x0a, 0x0e, 0x73, 0x61, 0x6b, 0x75, 0x72, 0x61, 0x6a, 0x6f, 0x73, 0x75, 0x69, 0x5f,
	0x64, 0x36, 0x10, 0x10, 0x12, 0x0c, 0x0a, 0x08, 0x63, 0x68, 0x6f, 0x66, 0x75, 0x5f, 0x64, 0x31,
	0x10, 0x15, 0x12, 0x0c, 0x0a, 0x08, 0x63, 0x68, 0x6f, 0x66, 0x75, 0x5f, 0x64, 0x32, 0x10, 0x16,
	0x12, 0x0c, 0x0a, 0x08, 0x63, 0x68, 0x6f, 0x66, 0x75, 0x5f, 0x64, 0x33, 0x10, 0x17, 0x12, 0x0c,
	0x0a, 0x08, 0x63, 0x68, 0x6f, 0x66, 0x75, 0x5f, 0x64, 0x34, 0x10, 0x18, 0x12, 0x0c, 0x0a, 0x08,
	0x63, 0x68, 0x6f, 0x66, 0x75, 0x5f, 0x64, 0x35, 0x10, 0x19, 0x12, 0x10, 0x0a, 0x0c, 0x68, 0x61,
	0x73, 0x68, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x31, 0x10, 0x1f, 0x12, 0x10, 0x0a, 0x0c,
	0x68, 0x61, 0x73, 0x68, 0x69, 0x6d, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x32, 0x10, 0x20, 0x12, 0x0f,
	0x0a, 0x0b, 0x68, 0x61, 0x63, 0x68, 0x69, 0x6f, 0x6a, 0x69, 0x5f, 0x64, 0x31, 0x10, 0x29, 0x12,
	0x0f, 0x0a, 0x0b, 0x68, 0x61, 0x63, 0x68, 0x69, 0x6f, 0x6a, 0x69, 0x5f, 0x64, 0x32, 0x10, 0x2a,
	0x22, 0x80, 0x01, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x53, 0x65, 0x6e, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x30, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55,
	0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45,
	0x44, 0x10, 0x02, 0x32, 0x3e, 0x0a, 0x03, 0x41, 0x74, 0x73, 0x12, 0x37, 0x0a, 0x0a, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x53,
	0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ats_proto_rawDescOnce sync.Once
	file_proto_ats_proto_rawDescData = file_proto_ats_proto_rawDesc
)

func file_proto_ats_proto_rawDescGZIP() []byte {
	file_proto_ats_proto_rawDescOnce.Do(func() {
		file_proto_ats_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ats_proto_rawDescData)
	})
	return file_proto_ats_proto_rawDescData
}

var file_proto_ats_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_ats_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ats_proto_goTypes = []interface{}{
	(SendStatusRequest_SensorName)(0), // 0: SendStatusRequest.SensorName
	(SendStatusResponse_Response)(0),  // 1: SendStatusResponse.Response
	(*SendStatusRequest)(nil),         // 2: SendStatusRequest
	(*SendStatusResponse)(nil),        // 3: SendStatusResponse
}
var file_proto_ats_proto_depIdxs = []int32{
	0, // 0: SendStatusRequest.sensor:type_name -> SendStatusRequest.SensorName
	1, // 1: SendStatusResponse.response:type_name -> SendStatusResponse.Response
	2, // 2: Ats.SendStatus:input_type -> SendStatusRequest
	3, // 3: Ats.SendStatus:output_type -> SendStatusResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ats_proto_init() }
func file_proto_ats_proto_init() {
	if File_proto_ats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ats_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ats_proto_goTypes,
		DependencyIndexes: file_proto_ats_proto_depIdxs,
		EnumInfos:         file_proto_ats_proto_enumTypes,
		MessageInfos:      file_proto_ats_proto_msgTypes,
	}.Build()
	File_proto_ats_proto = out.File
	file_proto_ats_proto_rawDesc = nil
	file_proto_ats_proto_goTypes = nil
	file_proto_ats_proto_depIdxs = nil
}
