apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-backend-external
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: soft-backend-external
  template:
    metadata:
      labels:
        app: soft-backend-external
    spec:
      containers:
        - name: soft-backend-external
          image: ghcr.io/ueckoken/plarail2022-external:4b7417c-1668778975 # {"$imagepolicy": "plarail2021:external"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: external-env
