apiVersion: v1
kind: Service
metadata:
  name: soft-backend-external
  namespace: plarail2021
  labels:
    app: soft-backend-external
spec:
  type: ClusterIP
  selector:
    app: soft-backend-external
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: grpc
      port: 9000
      protocol: TCP
      targetPort: 9000
