apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  values:
    additionalArguments:
      - --entryPoints.web.http.redirections.entryPoint.to: websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme: https
  chart:
    spec:
      chart: traefik
      version: "14.0.2"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 10m
