apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: "19.0.4"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 10m
