apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tlscert
  namespace: traefik
spec:
  secretName: cloudflare-cert
  dnsNames:
    - "*.chofufes2022.ueckoken.club"
    - "chofufes2022.ueckoken.club"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
