apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-oauth2-proxy-verify
  namespace: traefik
spec:
  forwardAuth:
    address: http:/oatuh2-proxy.oauth2-proxy:4180/oauth2/auth_or_start
    authResponseHeaders: "X-Forwarded-Uesr"
    trustForwardHeader: true
