apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: plarail2022-flux
  namespace: plarail2021
spec:
  interval: 1m
  path: ./manifests/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: plarail2022
  validation: client
