apiVersion: apps/v1
kind: Deployment
metadata:
  name: soft-python
  namespace: plarail2021
spec:
  selector:
    matchLabels:
      app: soft-python
  template:
    metadata:
      labels:
        app: soft-python
    spec:
      containers:
        - name: soft-python
          image: ghcr.io/ueckoken/plarail2022-frontend-python:27d82b2-1668657626 # {"$imagepolicy": "plarail2021:frontend-python"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: videocast
