name: compile_PB

on:
  push:
    paths:
      - "backend/proto/*"
      - ".github/workflows/compile-protocol-buffer.yml"
      - "backend/Makefile"
    branches-ignore:
      - "main"
      - "deployment"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: add path
        run: |-
          echo "$RUNNER_TEMP/protoc/bin" >> $GITHUB_PATH
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: run protoc
        run: |-
          curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.19.0/protoc-3.19.0-linux-x86_64.zip -o $RUNNER_TEMP/protoc.zip
          unzip -d $RUNNER_TEMP/protoc $RUNNER_TEMP/protoc.zip
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1

          mkdir -p $GITHUB_WORKSPACE/backend/internal/spec
          mkdir -p $GITHUB_WORKSPACE/backend/external/spec

          cd $GITHUB_WORKSPACE/backend/

          make pb
      - name: Count changes
        id: changes
        run: |
          # https://zenn.dev/snowcait/articles/18c9137f49e378#%E6%96%B9%E6%B3%95-2-%3A-jobs.%3Cjob_id%3E.steps.if
          git add -N . # 新規ファイルを含める
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: commit & push
        run: |
          git config --global user.name 'GITHUB ACTION BOT'
          git config --global user.email 'bot@example.com'
          git add .
          git commit -m "Update"
          git push
        if: steps.changes.outputs.count > 0
