name: compile_PB

on:
  push:
    paths:
      - "backend/proto/*"
      - ".github/workflows/compile-protocol-buffer.yml"
      - "backend/Makefile"
    branches-ignore:
      - "main"
      - "deployment"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Node in ats
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: add path
        run: |-
          echo "$RUNNER_TEMP/protoc/bin" >> $GITHUB_PATH
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: prepare protoc
        run: |-
          curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-linux-x86_64.zip -o $RUNNER_TEMP/protoc.zip
          unzip -d $RUNNER_TEMP/protoc $RUNNER_TEMP/protoc.zip
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          mkdir -p $GITHUB_WORKSPACE/backend/internal/spec
          mkdir -p $GITHUB_WORKSPACE/backend/external/spec
          mkdir -p $GITHUB_WORKSPACE/backend/ats/spec
          mkdir -p $GITHUB_WORKSPACE/backend/json2grpc/spec
      - name: prepare node protoc
        run: |-
          yarn install --frozen-lockfile
        working-directory: backend/ats
      - name: gen proto
        run: |-
          make pb
        working-directory: backend/
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
