name: Deploy internal

defaults:
  run:
    working-directory: ./backend/internal

on:
  push:
    branches: [deployment]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./backend/internal/go.mod
          cache: true
          cache-dependency-path: ./backend/internal/go.sum
      - name: Build Go binary
        run: |-
          make build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./backend/internal
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ueckoken/plarail2022-internal:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
