name: build speed control proxy

defaults:
  run:
    working-directory: ./backend/builtin/speed

on:
  push:
    paths:
      - ./backend/builtin/speed/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./backend/builtin/speed/go.mod
          cache: true
          cache-dependency-path: ./backend/builtin/speed/go.sum
      - name: Build Go binary
        run: |-
          make build_arm
      - uses: EndBug/add-and-commit@v9
