name: formatter
on:
  push:
    paths:
      - "frontend/**/*"
    branches-ignore:
      - "main"
      - "deployment"


jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend/"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn fmt
      - name: Count changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=count::$(git diff --name-only |wc -l)"
      - name: commit and push
        run: |
          git config --global user.name 'format BOT'
          git config --global user.email 'bot@example.com'
          git add .
          git commit -m 'format by prettier'
          git push
        if: steps.changes.outputs.count > 0

  prettier-videocast:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend/videoCast"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm
          cache-dependency-path: ./frontend/videoCast/package-lock.json
      - run: npm ci
      - run: npm run fmt
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: format BOT
          author_email: bot@example.com
          message: format by prettier
