name: formatter
on:
  push:
    branches-ignore:
      - "main"
      - "deployment"

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "frontend/site"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./frontend/site/.nvmrc
          cache: yarn
          cache-dependency-path: ./frontend/site/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn fmt
      - uses: EndBug/add-and-commit@v9
        with:
          message: format by prettier

  black-auto_operation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend/auto_operation"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ./backend/auto_operation/.python-version
          cache: pip
          cache-dependency-path: ./backend/auto_operation/requirements.dev.txt
      - run: pip install -r requirements.dev.txt
      - run: make format
      - uses: EndBug/add-and-commit@v9
        with:
          message: format by black
          default_author: github_actions

  black-multicaster:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "backend/multicaster"
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: ./backend/multicaster/.python-version
          cache: pip
          cache-dependency-path: ./backend/multicaster/requirements-dev.txt
      - run: pip install -r requirements-dev.txt
      - run: black .
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: format BOT
          author_email: bot@example.com
          message: format by black
