name: Deploy external

defaults:
  run:
    working-directory: ./backend/external

on:
  push:
    branches: [deployment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: ./backend/external/go.mod
          cache: true
          cache-dependency-path: ./backend/external/go.sum
      - name: Build Go binary
        run: |-
          make build
      - name: set tag
        run: |-
          export TIMESTUMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTAMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./backend/auto_operation
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ueckoken/plarail2022-auto-operation:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  backend-external:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/external
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: set tag
        run: |-
          export TIMESTAMP=$(date +%s)
          export SHA=$(echo ${{ github.sha }} | cut -c1-7)
          echo "IMAGE_TAG=$SHA-$TIMESTAMP" >> $GITHUB_ENV
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./backend/external
          platforms: linux/amd64
          push: true
          tags: ghcr.io/ueckoken/plarail2022-external:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
