name: build and publish image

on:
  push:
    branches:
      - "main"
      - "deployment"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate tag
        id: generate_tag
        shell: bash
        run: echo "::set-output name=tag::$(echo ${{ github.sha }} | cut -c1-7)-$(date +%s)"

      - name: Bake images
        uses: docker/bake-action@master
        env:
          TAG: ${{ steps.generate_tag.outputs.tag }}
        with:
          files: ./docker-bake.hcl
          push: ${{ github.event_name == 'push' && startsWith( steps.extract_branch.outputs.branch , 'deployment' ) }}
