name: Frontend build and test

defaults:
  run:
    working-directory: ./frontend/site

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/frontend/site/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./frontend/site/**/yarn.lock') }}-${{ hashFiles('./frontend/site/**.[jt]s', './frontend/site/**.[jt]sx') }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./frontend/site/.nvmrc
          cache: yarn
          cache-dependency-path: ./frontend/site/yarn.lock
      - name: dependency-install
        run: yarn install --frozen-lockfile --immutable
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
