name: Frontend build and test

defaults:
  run:
    working-directory: ./frontend

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('./frontend/**/yarn.lock') }}-${{ hashFiles('./frontend/**.[jt]s', './frontend/**.[jt]sx') }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./frontend/.nvmrc
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock
      - name: dependency-install
        run: yarn install --frozen-lockfile --immutable
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
